report_exclude:
  - .build/**
  - .make/**
  - build/**
  - Products/**
  - Derived/**
  - DerivedData/**
strict: true
retain_public: true
retain_objc_accessible: true
retain_codable_properties: true
clean_build: true
disable_update_check: true
format: xcode
