//
//  DeadcodeBuildConfig.swift
//  SwiftMkCore
//
//  Created by Alexander Goodkind <alex@goodkind.io> on 2026-06-05.
//  Copyright © 2026, all rights reserved.
//

import Foundation

// MARK: - DeadcodeBuildConfig

/// Builds the environment for the dead-code coverage build so swift-mk, not the
/// consumer, guarantees a complete, signing-independent index.
///
/// Two failure modes made the gate fail intermittently, both fixed here through a
/// single xcconfig that swift-mk points `xcodebuild` at with `XCODE_XCCONFIG_FILE`
/// (it overrides every target's settings, including a build wrapper's command-line
/// settings):
///
/// 1. Signing. The dead-code gate compiles only to fill the index store, then reads
///    it; it never needs a signed product, and indexing happens before signing. A
///    normal signed build can fail its provisioning step (xcodebuild exit 133) and
///    leave the index empty. `CODE_SIGNING_ALLOWED = NO` skips signing.
///
/// 2. Stale intermediates. A project that sends build intermediates outside the
///    derived-data directory (for example `SYMROOT = $(SRCROOT)/build`) keeps them
///    after a `rm -rf $(SWIFT_MK_DERIVED_DATA)`, so the next build is incremental,
///    skips compilation, and writes no index records, leaving the index empty even
///    though the build exits 0. Pointing `OBJROOT` inside the derived-data directory
///    makes the consumer's `rm` clear the build database too, so every coverage build
///    recompiles and the index is complete. Only `OBJROOT` is redirected, not
///    `SYMROOT`: a build's final products must stay where the consumer expects them,
///    since a step may copy a product from a fixed path (for example building a helper
///    app and copying it into place).
///
/// Only the coverage build is affected; a normal `build` still signs and keeps its
/// own intermediates.
enum DeadcodeBuildConfig {
    static let fileName = "deadcode.xcconfig"

    /// The header comment plus the settings that always apply: disable signing and
    /// force the index store on.
    static let baseContents = """
        // Generated by swift-mk for the dead-code coverage build only.
        // The dead-code gate needs the Xcode index, not a signed product, and
        // indexing happens before signing, so signing is disabled here to keep the
        // coverage build from failing on provisioning. Normal builds are unaffected.
        CODE_SIGNING_ALLOWED = NO
        CODE_SIGNING_REQUIRED = NO
        CODE_SIGN_IDENTITY = -
        COMPILER_INDEX_STORE_ENABLE = YES
        """

    /// The full xcconfig text. When a derived-data path is known, also redirect the
    /// build intermediates and products under it, so a `rm -rf` of that directory
    /// makes the next coverage build clean and the index complete.
    static func contents(derivedData: String) -> String {
        let trimmed = derivedData.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else {
            return baseContents
        }
        return baseContents + """

            // Keep build intermediates (the incremental build database) with the index
            // under the derived-data directory, so the consumer's
            // `rm -rf $(SWIFT_MK_DERIVED_DATA)` clears them too and every coverage build
            // recompiles rather than skipping and leaving the index empty. SYMROOT is
            // left alone so final products stay where the consumer expects them.
            OBJROOT = \(trimmed)/DeadcodeBuild/Intermediates.noindex
            """
    }

    /// Write the xcconfig under `makeDir` and return the environment that makes
    /// xcodebuild apply it. On a write failure the environment is empty, so the build
    /// still runs and the existing build-failure and completeness guards catch a bad
    /// index rather than this masking it.
    static func buildEnvironment(
        derivedData: String,
        makeDir: String = ".make"
    ) -> [String: String] {
        let path = (makeDir as NSString).appendingPathComponent(fileName)
        do {
            try FileManager.default.createDirectory(
                atPath: makeDir, withIntermediateDirectories: true)
            try contents(derivedData: derivedData).write(
                toFile: path, atomically: true, encoding: .utf8)
        } catch {
            Output.error(
                "deadcode: could not write \(path), coverage build keeps signing: \(error)")
            return [:]
        }
        let absolutePath = URL(fileURLWithPath: path).standardizedFileURL.path
        Output.info("deadcode: coverage build runs with code signing disabled via \(absolutePath)")
        return ["XCODE_XCCONFIG_FILE": absolutePath]
    }
}
