//
//  SigningBuildConfig.swift
//  SwiftMkCore
//
//  Created by Alexander Goodkind <alex@goodkind.io> on 2026-06-05.
//  Copyright © 2026, all rights reserved.
//

import Foundation

// MARK: - SigningBuildConfig

/// Builds the signing override xcconfig so swift-mk, not each consumer, owns the
/// build-time code-signing identity, team, and style.
///
/// It mirrors `DeadcodeBuildConfig`: a single xcconfig that `build`/`deploy` point
/// `xcodebuild` at with `XCODE_XCCONFIG_FILE`, which overrides every target's
/// settings, including Tuist's per-target ad-hoc default (`CODE_SIGN_IDENTITY = -`).
/// That default is the root cause of recurring drift, where a target that forgets
/// to forward the signing values silently signs ad-hoc ("Sign to Run Locally").
/// A top-precedence override removes the per-target forwarding entirely.
///
/// The style is inferred from the identity/team a consumer already sets for
/// `xcodebuild`, never chosen:
///
/// - identity `-`, team optional  -> ad-hoc signing (PR-check context)
/// - real identity plus a team    -> Manual / Developer ID signing (release context)
/// - empty identity plus a team   -> Automatic development signing (local-dev context)
/// - empty identity and no team   -> no override; an unsigned build still works
///
/// Only `build`/`deploy` apply it. The dead-code coverage build keeps its own
/// signing-disabled xcconfig, so this never re-enables signing for that gate.
public enum SigningBuildConfig {
    public static let fileName = "signing.xcconfig"

    /// The ad-hoc identity xcodebuild understands; a build with this signs without
    /// a provisioned certificate or team.
    static let adHocIdentity = "-"

    /// The xcconfig text for the given values, or nil when neither an identity nor a
    /// team is set. Returning nil keeps swift-mk from forcing anything, so a fully
    /// unset configuration still produces an unsigned build.
    public static func contents(identity: String, team: String, style: String) -> String? {
        let identity = identity.trimmingCharacters(in: .whitespaces)
        let team = team.trimmingCharacters(in: .whitespaces)
        let explicitStyle = style.trimmingCharacters(in: .whitespaces)
        guard !identity.isEmpty || !team.isEmpty else {
            return nil
        }
        let resolvedStyle = resolveStyle(identity: identity, explicit: explicitStyle)
        var lines = [
            "// Generated by swift-mk: the single source of build-time code signing.",
            "// XCODE_XCCONFIG_FILE points xcodebuild here, so these settings win over",
            "// every target's settings, including Tuist's per-target ad-hoc signing",
            "// default. Style follows from the identity and team a consumer already",
            "// sets; it is never chosen here.",
        ]
        if !identity.isEmpty {
            lines.append("CODE_SIGN_IDENTITY = \(identity)")
        }
        lines.append("CODE_SIGN_STYLE = \(resolvedStyle)")
        if !team.isEmpty {
            lines.append("DEVELOPMENT_TEAM = \(team)")
        }
        if identity == adHocIdentity {
            // Ad-hoc PR checks: allow signing but never require a provisioned
            // identity, so a target whose project marks signing required still builds.
            lines.append("CODE_SIGNING_ALLOWED = YES")
            lines.append("CODE_SIGNING_REQUIRED = NO")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Manual whenever an identity is named (ad-hoc `-` or a real certificate);
    /// Automatic only for an empty identity with a team. An explicit
    /// `CODE_SIGN_STYLE` always wins.
    private static func resolveStyle(identity: String, explicit: String) -> String {
        if !explicit.isEmpty {
            return explicit
        }
        if identity.isEmpty {
            return "Automatic"
        }
        return "Manual"
    }

    /// Read the signing inputs from the environment. The `SWIFT_MK_SIGN_*` names win
    /// over the bare `CODE_SIGN_IDENTITY` / `DEVELOPMENT_TEAM` / `CODE_SIGN_STYLE`
    /// names consumers already define for `xcodebuild`, so a consumer can be explicit
    /// without colliding with its own xcodebuild variables.
    public static func environmentInputs() -> (identity: String, team: String, style: String) {
        let identity = Env.get("SWIFT_MK_SIGN_IDENTITY", Env.get("CODE_SIGN_IDENTITY"))
        let team = Env.get("SWIFT_MK_SIGN_TEAM", Env.get("DEVELOPMENT_TEAM"))
        let style = Env.get("SWIFT_MK_SIGN_STYLE", Env.get("CODE_SIGN_STYLE"))
        return (identity, team, style)
    }

    /// Write the xcconfig from the environment inputs and return its absolute path,
    /// or nil when no override applies.
    public static func write(makeDir: String = ".make") -> String? {
        let inputs = environmentInputs()
        return write(
            identity: inputs.identity, team: inputs.team, style: inputs.style, makeDir: makeDir)
    }

    /// Write the xcconfig for explicit values and return its absolute path. Returns
    /// nil when no override applies or the write fails; on a write failure the build
    /// proceeds with its existing signing rather than being blocked by this.
    public static func write(
        identity: String, team: String, style: String, makeDir: String
    ) -> String? {
        guard let text = contents(identity: identity, team: team, style: style) else {
            return nil
        }
        let path = (makeDir as NSString).appendingPathComponent(fileName)
        do {
            try FileManager.default.createDirectory(
                atPath: makeDir, withIntermediateDirectories: true)
            try text.write(toFile: path, atomically: true, encoding: .utf8)
        } catch {
            Output.error(
                "signing: could not write \(path), build keeps its existing signing: \(error)")
            return nil
        }
        let absolutePath = URL(fileURLWithPath: path).standardizedFileURL.path
        Output.info("signing: build signs via \(absolutePath)")
        return absolutePath
    }
}
