//
//  SigningBuildConfig.swift
//  SwiftMkCore
//
//  Created by Alexander Goodkind <alex@goodkind.io> on 2026-06-05.
//  Copyright © 2026, all rights reserved.
//

import Foundation

// MARK: - SigningBuildConfig

/// Builds the signing override xcconfig so swift-mk, not each consumer, owns the
/// build-time code-signing identity, team, and style.
///
/// It mirrors `DeadcodeBuildConfig`: a single xcconfig that `build`/`deploy` point
/// `xcodebuild` at with `XCODE_XCCONFIG_FILE`, which overrides every target's
/// settings, including Tuist's per-target ad-hoc default (`CODE_SIGN_IDENTITY = -`).
/// That default is the root cause of recurring drift, where a target that forgets
/// to forward the signing values silently signs ad-hoc ("Sign to Run Locally").
/// A top-precedence override removes the per-target forwarding entirely.
///
/// The style is inferred from the identity/team a consumer already sets for
/// `xcodebuild`, never chosen:
///
/// - identity `-`, team optional  -> ad-hoc signing (PR-check context)
/// - real identity plus a team    -> Manual / Developer ID signing (release context)
/// - empty identity plus a team   -> Automatic development signing (local-dev context)
/// - empty identity and no team   -> no override; an unsigned build still works
///
/// Only `build`/`deploy` apply it. The dead-code coverage build keeps its own
/// signing-disabled xcconfig, so this never re-enables signing for that gate.
public enum SigningBuildConfig {
    public static let fileName = "signing.xcconfig"

    /// The ad-hoc identity xcodebuild understands; a build with this signs without
    /// a provisioned certificate or team.
    static let adHocIdentity = "-"

    /// The xcconfig text for the given values, or nil when neither an identity nor a
    /// team is set. Returning nil keeps swift-mk from forcing anything, so a fully
    /// unset configuration still produces an unsigned build.
    /// Header comment emitted at the top of the generated xcconfig.
    static let header = """
        // Generated by swift-mk: the single source of build-time code signing.
        // XCODE_XCCONFIG_FILE points xcodebuild here, so these settings win over
        // every target's settings, including Tuist's per-target ad-hoc signing
        // default. Style follows from the identity and team a consumer already
        // sets; it is never chosen here.
        """

    static func contents(identity: String, team: String, style: String) -> String? {
        let trimmedIdentity = identity.trimmingCharacters(in: .whitespaces)
        let trimmedTeam = team.trimmingCharacters(in: .whitespaces)
        let trimmedStyle = style.trimmingCharacters(in: .whitespaces)
        guard !trimmedIdentity.isEmpty || !trimmedTeam.isEmpty else {
            return nil
        }
        let resolvedStyle = resolveStyle(identity: trimmedIdentity, explicit: trimmedStyle)
        let identityLine =
            trimmedIdentity.isEmpty ? "" : "CODE_SIGN_IDENTITY = \(trimmedIdentity)\n"
        let teamLine = trimmedTeam.isEmpty ? "" : "DEVELOPMENT_TEAM = \(trimmedTeam)\n"
        // Ad-hoc PR checks: allow signing but never require a provisioned identity,
        // so a target whose project marks signing required still builds.
        let adHocLines =
            trimmedIdentity == adHocIdentity
            ? "CODE_SIGNING_ALLOWED = YES\nCODE_SIGNING_REQUIRED = NO\n" : ""
        return header + "\n" + identityLine + "CODE_SIGN_STYLE = \(resolvedStyle)\n" + teamLine
            + adHocLines
    }

    /// Manual whenever an identity is named (ad-hoc `-` or a real certificate);
    /// Automatic only for an empty identity with a team. An explicit
    /// `CODE_SIGN_STYLE` always wins.
    private static func resolveStyle(identity: String, explicit: String) -> String {
        if !explicit.isEmpty {
            return explicit
        }
        if identity.isEmpty {
            return "Automatic"
        }
        return "Manual"
    }

    /// The signing inputs resolved from the environment.
    public struct Inputs {
        public let identity: String
        public let team: String
        public let style: String
    }

    /// Read the signing inputs from the environment. The `SWIFT_MK_SIGN_*` names win
    /// over the bare `CODE_SIGN_IDENTITY` / `DEVELOPMENT_TEAM` / `CODE_SIGN_STYLE`
    /// names consumers already define for `xcodebuild`, so a consumer can be explicit
    /// without colliding with its own xcodebuild variables.
    public static func environmentInputs() -> Inputs {
        Inputs(
            identity: Env.get("SWIFT_MK_SIGN_IDENTITY", Env.get("CODE_SIGN_IDENTITY")),
            team: Env.get("SWIFT_MK_SIGN_TEAM", Env.get("DEVELOPMENT_TEAM")),
            style: Env.get("SWIFT_MK_SIGN_STYLE", Env.get("CODE_SIGN_STYLE")))
    }

    /// Read the signing inputs, the environment first and then the given xcconfig
    /// files for any value the environment leaves blank. The `make` prelude
    /// inline-passes these as make variables, but a tool that runs `xcodebuild`
    /// without that prelude has no such variables, so it passes its gitignored
    /// local xcconfig and the same values still reach the override.
    public static func resolvedInputs(localXcconfigPaths: [String] = []) -> Inputs {
        let environment = environmentInputs()
        var identity = environment.identity.trimmingCharacters(in: .whitespaces)
        var team = environment.team.trimmingCharacters(in: .whitespaces)
        var style = environment.style.trimmingCharacters(in: .whitespaces)
        for path in localXcconfigPaths {
            let values = xcconfigValues(atPath: path)
            if identity.isEmpty {
                identity = values["CODE_SIGN_IDENTITY"] ?? ""
            }
            if team.isEmpty {
                team = values["DEVELOPMENT_TEAM"] ?? ""
            }
            if style.isEmpty {
                style = values["CODE_SIGN_STYLE"] ?? ""
            }
        }
        return Inputs(identity: identity, team: team, style: style)
    }

    /// The number of components a parsed `KEY = value` line splits into.
    private static let keyAndValueComponentCount = 2

    /// Parse `KEY = value` lines from an xcconfig file into a dictionary, ignoring
    /// blank lines, comments, and trailing `//` or `;` segments, and stripping
    /// surrounding quotes. Returns an empty dictionary on any read failure, so a
    /// missing or unreadable file simply contributes nothing.
    static func xcconfigValues(atPath path: String) -> [String: String] {
        let contents: String
        do {
            contents = try String(contentsOfFile: path, encoding: .utf8)
        } catch {
            return [:]
        }
        var values: [String: String] = [:]
        for rawLine in contents.components(separatedBy: .newlines) {
            var line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("//") || line.hasPrefix("#") {
                continue
            }
            if let comment = line.range(of: "//") {
                line = String(line[..<comment.lowerBound]).trimmingCharacters(in: .whitespaces)
            }
            if let semicolon = line.firstIndex(of: ";") {
                line = String(line[..<semicolon]).trimmingCharacters(in: .whitespaces)
            }
            let parts = line.split(
                separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
            guard parts.count == keyAndValueComponentCount else {
                continue
            }
            let key = parts[0].trimmingCharacters(in: .whitespaces)
            let value = parts[1]
                .trimmingCharacters(in: .whitespaces)
                .trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
            if !key.isEmpty {
                values[key] = value
            }
        }
        return values
    }

    /// Write the xcconfig from the environment inputs and return its absolute path,
    /// or nil when no override applies.
    public static func write(makeDir: String = ".make") -> String? {
        let inputs = environmentInputs()
        return write(
            identity: inputs.identity, team: inputs.team, style: inputs.style, makeDir: makeDir)
    }

    /// Write the xcconfig for explicit values and return its absolute path. Returns
    /// nil when no override applies or the write fails; on a write failure the build
    /// proceeds with its existing signing rather than being blocked by this.
    public static func write(
        identity: String, team: String, style: String, makeDir: String
    ) -> String? {
        guard let text = contents(identity: identity, team: team, style: style) else {
            return nil
        }
        let path = (makeDir as NSString).appendingPathComponent(fileName)
        do {
            try FileManager.default.createDirectory(
                atPath: makeDir, withIntermediateDirectories: true)
            try text.write(toFile: path, atomically: true, encoding: .utf8)
        } catch {
            Output.error(
                "signing: could not write \(path), build keeps its existing signing: \(error)")
            return nil
        }
        let absolutePath = URL(fileURLWithPath: path).standardizedFileURL.path
        Output.info("signing: build signs via \(absolutePath)")
        return absolutePath
    }

    /// Apply the signing override to the current process environment so a tool that
    /// runs `xcodebuild` itself, without the `make build`/`deploy` prelude, still
    /// signs through swift-mk. It is a no-op when `XCODE_XCCONFIG_FILE` is already
    /// set, so a value the make prelude exported always wins. `setenv` uses
    /// `overwrite: 0` for the same reason. Best-effort: it returns nil and leaves
    /// the build to its existing signing when no override applies or the write
    /// fails, rather than blocking the build. Returns the override path on success.
    @discardableResult
    public static func applyEnvironmentOverride(
        localXcconfigPaths: [String] = [], makeDir: String = ".make"
    ) -> String? {
        let existing = Env.get("XCODE_XCCONFIG_FILE").trimmingCharacters(in: .whitespaces)
        if !existing.isEmpty {
            return nil
        }
        let inputs = resolvedInputs(localXcconfigPaths: localXcconfigPaths)
        guard
            let path = write(
                identity: inputs.identity,
                team: inputs.team,
                style: inputs.style,
                makeDir: makeDir)
        else {
            return nil
        }
        setenv("XCODE_XCCONFIG_FILE", path, 0)
        return path
    }
}
