name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    with:
      targets: '["smoke-fetch","lint","build","test","audit"]'
    secrets: inherit
